[COMPOSITE] Add composite qualifier to steps

diff --git a/.github/workflows/steps/check_branch_exist.yml b/.github/workflows/steps/check_branch_exist.yml
--- a/.github/workflows/steps/check_branch_exist.yml
+++ b/.github/workflows/steps/check_branch_exist.yml
@@ -1,23 +1,24 @@
 name: Checking branch exist
-runs-on: ubuntu-latest
-steps:
-  - name: Checking if target branch exists
-    run: |
-      echo "Fetching available branches for target..."
-      response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-      "$REMOTE_REPOSITORY_URL")
+runs:
+    using: "composite"
+    steps:
+      - name: Checking if target branch exists
+        run: |
+          echo "Fetching available branches for target..."
+          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+          "$REMOTE_REPOSITORY_URL")
     
-      # Check if curl was successful
-      if [ $? -ne 0 ]; then
-        echo "Error: Failed to fetch branches for target"
-        exit 1
-      fi
-      echo "Successfully fetched available branches from remote"
+          # Check if curl was successful
+          if [ $? -ne 0 ]; then
+            echo "Error: Failed to fetch branches for target"
+            exit 1
+          fi
+          echo "Successfully fetched available branches from remote"
 
-      # Check if the branch exists in the fetched response
-      if echo "$response" | jq '.[].name' | awk '{print $1}' | grep -q "$TARGET_BRANCH"; then
-        echo "Found "$TARGET_BRANCH" on remote"
-      else 
-        echo "Error: $TARGET_BRANCH not found on remote"
-        exit 1
-      fi
+          # Check if the branch exists in the fetched response
+          if echo "$response" | jq '.[].name' | awk '{print $1}' | grep -q "$TARGET_BRANCH"; then
+            echo "Found "$TARGET_BRANCH" on remote"
+          else 
+            echo "Error: $TARGET_BRANCH not found on remote"
+            exit 1
+          fi
diff --git a/.github/workflows/steps/check_user_input.yml b/.github/workflows/steps/check_user_input.yml
--- a/.github/workflows/steps/check_user_input.yml
+++ b/.github/workflows/steps/check_user_input.yml
@@ -1,15 +1,16 @@
 name: Checking release branch exist
-runs-on: ubuntu-latest
-steps:
-  - name: Checking user input parameters 
-    run: |
-      # Ensure origin is correctly set
-      git remote -v || (echo "Error: No remote repository found." && exit 1)
+runs:
+    using: "composite"
+    steps:
+      - name: Checking user input parameters 
+        run: |
+          # Ensure origin is correctly set
+          git remote -v || (echo "Error: No remote repository found." && exit 1)
 
-      # Try fetching the remote branches and check if the specific branch exists
-      if git ls-remote --heads origin "${{ github.event.inputs.build_origin_branch }}" | awk '{print $2}' | grep -q "refs/heads/${{ github.event.inputs.build_origin_branch }}"; then
-        echo "Found ${{ github.event.inputs.build_origin_branch }} on remote"
-      else 
-        echo "Error: ${{ github.event.inputs.build_origin_branch }} not found on remote"
-        exit 1
-      fi
+          # Try fetching the remote branches and check if the specific branch exists
+          if git ls-remote --heads origin "${{ github.event.inputs.build_origin_branch }}" | awk '{print $2}' | grep -q "refs/heads/${{ github.event.inputs.build_origin_branch }}"; then
+            echo "Found ${{ github.event.inputs.build_origin_branch }} on remote"
+          else 
+            echo "Error: ${{ github.event.inputs.build_origin_branch }} not found on remote"
+            exit 1
+          fi
diff --git a/.github/workflows/steps/checkout_to_new_branch.yml b/.github/workflows/steps/checkout_to_new_branch.yml
--- a/.github/workflows/steps/checkout_to_new_branch.yml
+++ b/.github/workflows/steps/checkout_to_new_branch.yml
@@ -1,15 +1,16 @@
 name: Checkout to a new branch
-runs-on: ubuntu-latest
-steps:
-  - name: Checkout to a new branch
-    run: |
-      echo "Configuring branch on origin repository"
-      if [[ "${{ env.RELEASE_BRANCH }}" == "main" ]] || [[ "${{ env.RELEASE_BRANCH }}" == "master" ]]; then
-        echo "Skip checkout for main/master branch"
-      elif git ls-remote --heads origin "${{ env.RELEASE_BRANCH }}" | grep -q "${{ env.RELEASE_BRANCH }}"; then
-        echo "Error: ${{ env.RELEASE_BRANCH }} already exists on Remote"
-        exit 1
-      else
-        echo "Switching to a new branch ${{ env.RELEASE_BRANCH }}"
-        git checkout -b ${{ env.RELEASE_BRANCH }}
-      fi
+runs:
+    using: "composite"
+    steps:
+      - name: Checkout to a new branch
+        run: |
+          echo "Configuring branch on origin repository"
+          if [[ "${{ env.RELEASE_BRANCH }}" == "main" ]] || [[ "${{ env.RELEASE_BRANCH }}" == "master" ]]; then
+            echo "Skip checkout for main/master branch"
+          elif git ls-remote --heads origin "${{ env.RELEASE_BRANCH }}" | grep -q "${{ env.RELEASE_BRANCH }}"; then
+            echo "Error: ${{ env.RELEASE_BRANCH }} already exists on Remote"
+            exit 1
+          else
+            echo "Switching to a new branch ${{ env.RELEASE_BRANCH }}"
+            git checkout -b ${{ env.RELEASE_BRANCH }}
+          fi
diff --git a/.github/workflows/steps/set_up_branches_checkmark.yml b/.github/workflows/steps/set_up_branches_checkmark.yml
--- a/.github/workflows/steps/set_up_branches_checkmark.yml
+++ b/.github/workflows/steps/set_up_branches_checkmark.yml
@@ -1,16 +1,17 @@
 name: Set up branches based on checkmark input
-runs-on: ubuntu-latest
-steps:
-  - name: Set up branches based on checkmark input
-    id: set_branches
-    run: |
-      echo "Validating checkmark set"
-      if [ "${{ github.event.inputs.main_checkmark }}" == "true" ]; then
-        echo "Building from main branches"
-        echo "CLIENT1_BRANCH=main" >> $GITHUB_ENV
-        echo "CLIENT2_BRANCH=main" >> $GITHUB_ENV
-        echo "RELEASE_BRANCH=main" >> $GITHUB_ENV
-      else
-        echo "Error: checkmark was not set"
-        exit 1
-      fi
+runs:
+    using: "composite"
+    steps:
+      - name: Set up branches based on checkmark input
+        id: set_branches
+        run: |
+          echo "Validating checkmark set"
+          if [ "${{ github.event.inputs.main_checkmark }}" == "true" ]; then
+            echo "Building from main branches"
+            echo "CLIENT1_BRANCH=main" >> $GITHUB_ENV
+            echo "CLIENT2_BRANCH=main" >> $GITHUB_ENV
+            echo "RELEASE_BRANCH=main" >> $GITHUB_ENV
+          else
+            echo "Error: checkmark was not set"
+            exit 1
+          fi
diff --git a/.github/workflows/steps/validate_release_version.yml b/.github/workflows/steps/validate_release_version.yml
--- a/.github/workflows/steps/validate_release_version.yml
+++ b/.github/workflows/steps/validate_release_version.yml
@@ -1,35 +1,36 @@
 name: Checking release branch exist
-runs-on: ubuntu-latest
-steps:
-  - name: Validate and check release version
-    run: |
-            # Get the release version from the input
-            RELEASE_VERSION=${{ github.event.inputs.release_version }}
-            echo "Validate release version compliance"
-            # Validate the version format (e.g. v1.2.3)
-            if [[ ! "$RELEASE_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-                echo "Error: Invalid version format. The version should be in the format (e.g. v1.2.3)"
-                exit 1
-            fi
-
-            echo "Fetching latest tag from repo"
-            # Get the latest tag from the repository
-                LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "none")
-
-            if [ "$LATEST_TAG" = "none" ]; then
-                echo "Warning: No tags found in the repository."
-                LATEST_TAG="0.0.0"  # Set a default version if needed
-            fi
-            
-            # If no tags are found, set a default version
-            if [ -z "$LATEST_TAG" ]; then
-                echo "No tags found in the repository. This will be the first release."
-            else
-                # Compare versions
-                if [[ "$(echo -e "$RELEASE_VERSION\n$LATEST_TAG" | sort -V | head -n1)" == "$RELEASE_VERSION" ]]; then
-                echo "Error: Release version $RELEASE_VERSION must be higher than the latest tag $LATEST_TAG."
-                exit 1
-                else
-                echo "Release version $RELEASE_VERSION is valid and higher than the latest tag $LATEST_TAG."
+runs:
+    using: "composite"
+    steps:
+      - name: Validate and check release version
+        run: |
+                # Get the release version from the input
+                RELEASE_VERSION=${{ github.event.inputs.release_version }}
+                echo "Validate release version compliance"
+                # Validate the version format (e.g. v1.2.3)
+                if [[ ! "$RELEASE_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+                    echo "Error: Invalid version format. The version should be in the format (e.g. v1.2.3)"
+                    exit 1
                 fi
-            fi
+
+                echo "Fetching latest tag from repo"
+                # Get the latest tag from the repository
+                    LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "none")
+
+                if [ "$LATEST_TAG" = "none" ]; then
+                    echo "Warning: No tags found in the repository."
+                    LATEST_TAG="0.0.0"  # Set a default version if needed
+                fi
+            
+                # If no tags are found, set a default version
+                if [ -z "$LATEST_TAG" ]; then
+                    echo "No tags found in the repository. This will be the first release."
+                else
+                    # Compare versions
+                    if [[ "$(echo -e "$RELEASE_VERSION\n$LATEST_TAG" | sort -V | head -n1)" == "$RELEASE_VERSION" ]]; then
+                    echo "Error: Release version $RELEASE_VERSION must be higher than the latest tag $LATEST_TAG."
+                    exit 1
+                    else
+                    echo "Release version $RELEASE_VERSION is valid and higher than the latest tag $LATEST_TAG."
+                    fi
+                fi
