[CI-CD] Repairing code

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -43,14 +43,16 @@ jobs:
             git fetch --all
             # Check if the branch exists remotely
             if git ls-remote --heads origin ${{ github.event.inputs.client1_branch }}; then
-                # If it exists, checkout the branch
-                git checkout ${{ github.event.inputs.client1_branch }}
+                # If the branch exists remotely, checkout and track the branch
+                git checkout -t origin/${{ github.event.inputs.client1_branch }}
             else
-                # If it doesn't exist, create and track the branch from origin
-                git checkout -b ${{ github.event.inputs.client1_branch }} origin/${{ github.event.inputs.client1_branch }}
+                # If the branch doesn't exist remotely, exit with error
+                echo "Error: Branch '${{ github.event.inputs.client1_branch }}' does not exist in origin."
+                exit 1
             fi
             # Pull the latest changes from the remote
             git pull origin ${{ github.event.inputs.client1_branch }}
+
 
 
 
@@ -60,14 +62,16 @@ jobs:
             git fetch --all
             # Check if the branch exists remotely
             if git ls-remote --heads origin ${{ github.event.inputs.client2_branch }}; then
-                # If it exists, checkout the branch
-                git checkout ${{ github.event.inputs.client2_branch }}
+                # If the branch exists remotely, checkout and track the branch
+                git checkout -t origin/${{ github.event.inputs.client2_branch }}
             else
-                # If it doesn't exist, create and track the branch from origin
-                git checkout -b ${{ github.event.inputs.client2_branch }} origin/${{ github.event.inputs.client2_branch }}
+                # If the branch doesn't exist remotely, exit with error
+                echo "Error: Branch '${{ github.event.inputs.client2_branch }}' does not exist in origin."
+                exit 1
             fi
             # Pull the latest changes from the remote
             git pull origin ${{ github.event.inputs.client2_branch }}
+
   
 
       - name: Update main repository submodule pointers
